package cn.dreamingfish.updater.engine;

public enum UpdateErrorCode {
    INVALID_BINDING,
    NETWORK_UNAVAILABLE,
    HTTP_ERROR,
    INVALID_SIGNATURE,
    INVALID_MANIFEST,
    WRONG_PROJECT,
    UNSUPPORTED_PLAYER_VERSION,
    REPLAY_DETECTED,
    LOCAL_STATE_INVALID,
    INSTANCE_BUSY,
    GAME_RUNNING,
    DOWNLOAD_FAILED,
    HASH_MISMATCH,
    LOCAL_CONTENT_CHANGED,
    PATH_UNSAFE,
    TRANSACTION_FAILED,
    RECOVERY_FAILED,
    CANCELLED
}
